# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/ip/blk_mem_flat/blk_mem_flat.xci
# IP: The module: 'blk_mem_flat' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/ip/blk_mem_flat/blk_mem_flat_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_flat'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/ip/blk_mem_flat/blk_mem_flat.xci
# IP: The module: 'blk_mem_flat' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/ip/blk_mem_flat/blk_mem_flat_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_flat'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
