# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2.xci
# IP: The module: 'microblaze_microblaze_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2.xci
# IP: The module: 'microblaze_microblaze_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_microblaze_0_2/microblaze_microblaze_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_microblaze_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
