# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1.xci
# IP: The module: 'microblaze_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1.xci
# IP: The module: 'microblaze_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Development/PROGH2/eindopdracht/eindopdracht.srcs/sources_1/bd/microblaze/ip/microblaze_lmb_bram_1/microblaze_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'microblaze_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
