set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
set_property IOSTANDARD LVCMOS33 [get_ports top_ps2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports top_ps2_data]
set_property IOSTANDARD LVCMOS33 [get_ports top_pwm]
set_property PACKAGE_PIN A15 [get_ports top_pwm]
set_property PACKAGE_PIN C17 [get_ports top_ps2_clk]
set_property PACKAGE_PIN B17 [get_ports top_ps2_data]
